### ISSUE TITLE
Containers that are attached to multiple networks sometimes don't bevome valid upstreams

### ISSUE THREAD

**Issue by heinebold** [invzhi/caddy-docker-upstreams#1]
To reproduce the problem, see the following setup:
The proxy is in a ntweork called "frontend". The app is in the "frontend" as well as the "backend" networks. The proxy doesn't detect any upstreams for the configured matchers.
If the app is not in the "backend" network, it is picked up correctly.
If I rename "backend" to "x_backend", it is picked up correctly! Apparently, it picks up the alphabetically first tenwork the container is attached to. My workaround was to rename my networks to "01-frontend" and "02-backend" but I think this is a funny hack, not a great solution.

It's happening around here, I suppose: https://github.com/invzhi/caddy-docker-upstreams/blob/ae857aaf46ad2ec13c80b826388454efd20dcd2a/upstreams.go#L112

**Comment by invzhi** [comment]
@heinebold Could you provide the docker-compose.yml?

**Comment by heinebold** [comment]
I created a compose.yml that contains everything you need to reproduce, fully inlined.

You should get an error for the container attached to two networks with the file as is, and make the container work by renaming the `backend` to something like `z_backend` or the `frontend` network to something like `a_frontend`.

[compose.yml](https://github.com/invzhi/caddy-docker-upstreams/files/15447000/compose.yml.txt) (remove .txt ending, github complained)

**Comment by invzhi** [comment]
Thanks for your feedback.
I added a label `com.caddyserver.http.network` to specify the network.
Would you like to test and give me some feedback?

**Comment by heinebold** [comment]
Thank you! Yes, of course, I'll experiment a bit in the evening (I'm only using it in a side project, it has to wait till my regular work is done)
I had kind of expected it to work just independent of the network / in all networks, but this implementation is probably the safest one wrt unexpected behavior.

**Comment by heinebold** [comment]
It works, but with one bug/problem: If the network is created via docker compose, you have to specify the final name of the network, which is the name you gave it, prefixed with the compose project's name.
In my example file, it doesn't work with `com.caddyserver.http.network: frontend`, you'd have to specify `com.caddyserver.http.network: example_frontend`, which would break once you touch the name of the project.

**Comment by invzhi** [comment]
Thank you, this is very valuable firsthand information. I will try to optimize this issue.

**Comment by invzhi** [comment]
Hey I added project prefix support in this commit, looking forward to your feedback.
https://github.com/invzhi/caddy-docker-upstreams/commit/526fa64b2bc0b5eb5a81940004a2d80606109345

**Comment by heinebold** [comment]
Thank you very much, this works great!
